### ISSUE TITLE
Add Support for Commands API


### ISSUE THREAD

**Issue by kristinpeterson** [attm2x/m2x-nanode#3]
Add support for the [Commands API](https://m2x.att.com/developer/documentation/v2/commands).

Per the [Limited Client Contribution Guidelines](https://github.com/attm2x/m2x-service/blob/master/LIMITED-CLIENT-CONTRIBUTIONS.md#supported-api-methods) only the following endpoints need to be supported for limited clients:

  - [`GET /devices/:id/commands`](https://m2x.att.com/developer/documentation/v2/commands#Device-s-List-of-Received-Commands)
  - [`PUT / devices/:id/commands/:id/process`](https://m2x.att.com/developer/documentation/v2/commands#Device-Marks-a-Command-as-Processed)
  - [`PUT /devices/:id/commands/:id/reject`](https://m2x.att.com/developer/documentation/v2/commands#Device-Marks-a-Command-as-Rejected)

**Comment by xxuejie** [comment]
Since we cannot have a content parser working in Nanode's environment, we cannot have `GET /devices/:id/commands`. All we can do here is to implement the rest 2 APIs.

@kristinpeterson Let me know if that works, or maybe we should look for certain workarounds?

**Comment by kristinpeterson** [comment]
:smile_cat:

**Comment by kristinpeterson** [comment]
@xxuejie, in that case, let's leave the Commands API out, as without the ability to list commands processing/rejecting a command is useless (as you've mentioned elsewhere)

Would one of our MQTT libraries work on the nanode?

**Comment by xxuejie** [comment]
@kristinpeterson Unfortunately, the problem is not HTTP vs MQTT, it is really the response content format we got from M2X. So, no, I don't think MQTT would work here.

**Comment by kristinpeterson** [comment]
@xxuejie the reason I ask is because if we were to use MQTT then listing the commands wouldn't be required on the device, the device can subscribe to the commands topic to receive commands and publish their response (process/reject). Even if the device goes offline they should still receive any commands that were published while they were away (@jemc correct me if I'm wrong there, this depends on the QoS level we're using).

List Commands is only necessary on devices using HTTP because they need to actively request commands, as opposed to MQTT where they can subscribe to their commands.

Am I missing something here?

**Comment by xxuejie** [comment]
Yeah, I understand what you are saying here, we have that kind of mechanism in MQTT, however, I think for this particular device, MQTT might be a far too powerful protocol to implement here, it just contains so many tiny details that would eat up all computing power and (most likely) memory of a nanode board.

What I envision this to work, is that besides a nanode board, a user might have a much more powerful chip aiding this work, such as a Pi working as a central control unit. So the Pi is in charge of fetching commands from M2X(either via MQTT or HTTP, either one is fine), then use some sort of radio technology to inform nanode of new commands, then nanode can perform the action, and accept/reject the command. Personally, I feel this is the only way it can work here.

**Comment by kristinpeterson** [comment]
Thank you for the explanation @xxuejie !

Closing this issue since this board cannot support the Commands API on it's own.
